name: Deploy Hexo Site

on:
  push:
    branches:
      - main  # 当代码推送到 main 分支时触发

  # 允许从 GitHub 的 Actions 标签页手动触发这个工作流
  workflow_dispatch:

# 设置全局权限，让工作流有权限写入内容
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      # 1. 从你的仓库中拉取代码
      - name: Checkout
        uses: actions/checkout@v4

      # 2. 安装 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # 3. 安装项目依赖
      - name: Install Dependencies
        run: npm ci

      # 4. 生成静态博客文件
      - name: Generate Static Files
        run: npx hexo generate

      # 5. 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          # 注意！这里的仓库名是 `<你的GitHub用户名>.github.io`
          external_repository: zzgpy1/zzgpy1.github.io
          # 使用秘密变量 `ACTIONS_DEPLOY_KEY` 进行身份验证
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: main  # 部署到目标仓库的 main 分支
          publish_dir: ./public
          commit_message: ${{ github.event.head_commit.message }}
